### ISSUE TITLE
url arguments

### ISSUE THREAD

**Issue by githingeorge** [jazzband/django-simple-menu#48] opened 2016-10-27 06:24 UTC
```
Menu.add_item("sidebar", MenuItem(
    "Tasks",
    reverse("project:task:list", args=[project.id]),
    weight=2,
    check=lambda request: request.user.has_perm('task.can_access'),
    icon="clipboard",),
)
```

how to get the project id in the above code??

**Comment by pvandriessche** [comment] 2017-06-05 13:00
I'm not sure if this is the nicest way, but for me it work to make some middleware to load my menu's based on the url arguments.
In the kwargs function you should be able to find your project id.

    class SimpleMiddleware(object):

        def process_view(self, request, func, args, kwargs):
            Menu.items.clear()
            Menu.add_item("sidebar", MenuItem(
                 "Tasks",
                  reverse("project:task:list", args=[kwargs['project.id']]),
                  weight=2,
                  check=lambda request: request.user.has_perm('task.can_access'),
                  icon="clipboard",))

                 return None

**Comment by kytta** [comment] 2022-05-08 18:29
This can be done with callable URLs. Please take a look at how the problem is described in #70 as well as the proposed solution in #71. Closing this.

**Closed by kytta** 2022-05-08 18:29 UTC
